{% set version = "3.40.1.0" %}
{% set sqlite_version = "3.40.1" %}

package:
  name: apsw
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/rogerbinns/apsw/archive/{{ version }}.tar.gz
  sha256: f0fe57bcd1ebc0439a1d95cad1716c6492dab81824c79e01101a72862eb18473

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - sqlite =={{ sqlite_version }}

  run:
    - python
    - sqlite =={{ sqlite_version }}

test:
  imports:
    - apsw

about:
  home: https://github.com/rogerbinns/apsw/
  license: OSI
  license_file: LICENSE
  summary: APSW stands for Another Python SQLite Wrapper.
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. It focuses translating between the complete SQLite C API and
    Python's C API. It is recommended to use the builtin sqlite3 module, unless
    you want SQLite specific functionality. The documentation has a section on
    the differences between APSW and sqlite3. APSW supports CPython 3.6
    onwards:
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
