{% set version = "3.49.2.0" %}
{% set sqlite_version = "3.48.0" %}

package:
  name: apsw
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/rogerbinns/apsw/releases/download/{{ version }}/apsw-{{ version }}.zip
  sha256: 6ffaf3a94cd25fb011a882c359f7938d27a6f765557b512a2c665c2e3243c442

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - pycalverter
    - python
    - setuptools
    - sqlite =={{ sqlite_version }}

  run:
    - python
    - sqlite =={{ sqlite_version }}
    - pycalverter

test:
  requires:
    - python
    - pip
  imports:
    - apsw
  commands:
    - pip check

about:
  home: https://github.com/rogerbinns/apsw/
  license: any-OSI
  license_file: LICENSE
  summary: APSW stands for Another Python SQLite Wrapper.
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. It focuses translating between the complete SQLite C API and
    Python's C API. It is recommended to use the builtin sqlite3 module, unless
    you want SQLite specific functionality. The documentation has a section on
    the differences between APSW and sqlite3. APSW supports CPython 3.6
    onwards:
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
