{% set version = "3.38.5-r1" %}
{% set sqlite_version = "3.38.5" %}

package:
  name: apsw
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/rogerbinns/apsw/archive/{{ version }}.tar.gz
  sha256: 3b2be56f391f036d1299ac63285e5f29b1363028848b43c86324ec3c4beea4e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - sqlite =={{ sqlite_version }}

  run:
    - python
    - sqlite =={{ sqlite_version }}

test:
  imports:
    - apsw

about:
  home: https://github.com/rogerbinns/apsw/
  license: OSI
  license_file: LICENSE
  summary: APSW stands for Another Python SQLite Wrapper.
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. In contrast to other wrappers such as pysqlite it focuses on being
    a minimal layer over SQLite attempting just to translate the complete
    SQLite API into Python. The documentation has a section on the differences
    between APSW and pysqlite. APSW supports CPython 2.3 onwards and CPython
    3.1 onwards.
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
