{% set name = "apsw" %}
{% set version = "3.23.1-r1" %}
{% set sha256 = "692936799f8edfae371709fb948c446ea9e7d6fff5993bc9af6fd579c887f641" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", ".") }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/rogerbinns/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - sqlite 3.23.1
    - toolchain

  run:
    - python
    - sqlite 3.23.1

test:
  imports:
    - apsw

about:
  home: https://github.com/rogerbinns/apsw/
  license: OSI
  license_file: LICENSE
  summary: 'APSW stands for Another Python SQLite Wrapper.'
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. In contrast to other wrappers such as pysqlite it focuses on being
    a minimal layer over SQLite attempting just to translate the complete
    SQLite API into Python. The documentation has a section on the differences
    between APSW and pysqlite. APSW supports CPython 2.3 onwards and CPython
    3.1 onwards.
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
