{% set version = "3.51.0.0" %}
{% set sqlite_version = "3.51.0" %}

package:
  name: apsw
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/rogerbinns/apsw/releases/download/{{ version }}/apsw-{{ version }}.zip
  sha256: bce744d323080b40800e1c69297def870309e3cff5d688c814c13317d254bec7

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - libsqlite =={{ sqlite_version }}

  run:
    - python
    - libsqlite =={{ sqlite_version }}

test:
  requires:
    - python
    - pip
  imports:
    - apsw
  commands:
    - pip check

about:
  home: https://github.com/rogerbinns/apsw/
  license: any-OSI
  license_file: LICENSE
  summary: APSW stands for Another Python SQLite Wrapper.
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. It focuses translating between the complete SQLite C API and
    Python's C API. It is recommended to use the builtin sqlite3 module, unless
    you want SQLite specific functionality. The documentation has a section on
    the differences between APSW and sqlite3. APSW supports CPython 3.6
    onwards:
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
