{% set version = "3.25.2-r1" %}

package:
  name: apsw
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/rogerbinns/apsw/archive/{{ version }}.tar.gz
  sha256: 5a54f673a8a878d31e530ef2ce7faf679545f2cdff7dd0a3b1ce58187bfb1cf7

build:
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - sqlite

  run:
    - python
    - sqlite

test:
  imports:
    - apsw

about:
  home: https://github.com/rogerbinns/apsw/
  license: OSI
  license_file: LICENSE
  summary: 'APSW stands for Another Python SQLite Wrapper.'
  description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. In contrast to other wrappers such as pysqlite it focuses on being
    a minimal layer over SQLite attempting just to translate the complete
    SQLite API into Python. The documentation has a section on the differences
    between APSW and pysqlite. APSW supports CPython 2.3 onwards and CPython
    3.1 onwards.
  doc_url: https://rogerbinns.github.io/apsw/pysqlite.html
  dev_url: https://github.com/rogerbinns/apsw

extra:
  recipe-maintainers:
    - stuertz
