appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FUSpAURmcQpFWBoml8yD+DvHD+Fi9vBImrckX2pwwfbM3GWLWFPovlRYkXt2X5IP4TcHujgF+O70M6I1lX9ZRcsQ1lLXXyXHnVZLo2CRV54Gxs2rh5seV1mbPhAutBRrD5EE8Pi7pwVDZxA5UlJDmMSMueW8tdKs7A2Y4Icfo5tVbliuluHQvyqz7+j40MP9rh/lTy2H7ZSyzEIHxvyiKgt2PxTldDP8D4E3Go1HEGD2J+defRg+4Kv62c6AI2yvglMYJ2cPoPz/uipuKwgTJJKx6BtBusPcyVXM2aB930aLHHkakKCs6JeWLE6qquS2UiPEQwy+eTnVNdKdG9m4NRW3M8lCumS77as4re8c2REmhWBoxWbDm/D61cQIJOuo7wg+Z4qwVo1QV90clxnZRumuyPgYcqfW4afNCRH50KkYAvx0qGA/ZqcknUxzMz73AN2PuDLq6gBk0yGh6Z9bTcoL4e/Tt4c6YX1fBoJLC043K0ClYFw+0BgJtSL515+wvPLiMCupcMSJjmZ4KFbXTWl80ErlVM/bYGhIjSOBlZ6DpsLPDoyG0nK9eSmHyXJhidpn3YXamt9mJzWsMycfV/TbXmQa5QxEgL9ElNh2mFL4WEjTbSGijXaaee+T5B6E/S99YfcoesRuoLZvQ8fq4H/RYhvxxyXgN5Nxweb7emE=}
provider:
  win: azure
conda_forge_output_validation: false
